name: Pruebadx
favicon: null
layout_spectrum: 0.8663380288053304
typography_spectrum: 0.03700555209070444
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#B8B42D'
    - '#697A21'
    - '#FFFCE8'
    - '#3E363F'
    - '#DD403A'
  brandStrength: 0.394561784574762
  lightness: 0.9588514701463282
  saturation: 0.12077438528649509
  rhythmicContrast: 0.8066743933595717
purpose: []
